name: CI

on:
    push:

env:
  ENTRYPOINT: main.py
  UV_VERSION: 0.6.2
  PYTHON_VERSION_FILE: ".python-version"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ env.PYTHON_VERSION_FILE }}

      - name: Install the project
        run: uv sync

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ env.PYTHON_VERSION_FILE }}

      - name: Install the project
        run: uv sync

      # - name: Run MyPy
      #   run: uv run mypy -p placefinder
